grpc/grpc.github.io

- docs/index.md
I thought I've fixed this before but obviously I created a PR against wrong branch. Sorry.
Fixes https://github.com/grpc/grpc/issues/4098
> Fix protoc usage

- docs/guides/auth.md
These changes mirror the earlier C# changes
> Updated auth document with 0.12 Node changes

- docs/guides/auth.md
There's been quite a lot of changes in the C++ API since this document was last updated.
Assigning to @yang-g now to check the C++ sample code but @a11r and @LisaFC will have the final say on the text.
> Changing auth documentation for C++.

- docs/guides/auth.md
> Updated auth document with 0.12 Ruby changes

- docs/guides/auth.md
with the new Call Credentials options.
> Update PHP auth code example

- docs/guides/auth.md
Also updated the URLs used in the Node auth examples
CC @jboeuf
> Updated Ruby auth doc with newest Ruby changes

- docs/guides/auth.md
* Insecure ChannelCredentials is now explicit
* Update section headings to be consistent with other languages
> Update PHP auth example

- _data/config.yml
- _layouts/docs.html
- docs/tutorials/auth/oauth2-objective-c.md
Only merge this after release-0_13 has been released.
> Update website links to release-0_13

- docs/reference/index.html
repeating the doc link from the menu to the main page
> adding golang api reference

- docs/installation/c.md
- docs/tutorials/basic/c.md
- docs/tutorials/basic/python.md
- docs/tutorials/basic/ruby.md
INSTALL is now a .md doc. See grpc/grpc#5243
> Update link to base INSTALL doc

- docs/tutorials/basic/node.md
> Fix node.js route guide commands

- docs/guides/auth.md
Content largely from https://github.com/grpc/grpc-java/blob/master/SECURITY.md
> Added auth examples for Java

- docs/index.md
Fixes https://github.com/grpc/grpc.github.io/issues/139
> Replace underscores in Ruby snippet with HTML entities

- docs/index.md
Fixes https://github.com/grpc/grpc.github.io/issues/142
> documented single argument and return for methods

- docs/tutorials/basic/c.md
- docs/tutorials/basic/csharp.md
- docs/tutorials/basic/go.md
- docs/tutorials/basic/java.md
- docs/tutorials/basic/objective-c.md
- docs/tutorials/basic/python.md
Fixes https://github.com/grpc/grpc.github.io/issues/160
> Proto3 information update

- _posts/2016-3-24-pubsub.md
Ready for publication whenever...
> Pubsub blog post

- docs/tutorials/basic/java.md
Fixes https://github.com/grpc/grpc.github.io/issues/171
> Fixed broken link to installation/setup instructions

- docs/tutorials/basic/java.md
Updated snippets with the correct channel and server builders.
Fixes https://github.com/grpc/grpc.github.io/issues/170
> Updated tutorial snippets

- docs/index.md
- docs/tutorials/basic/csharp.md
This should fix the documentation issues mentioned in  https://github.com/grpc/grpc/issues/6151.
> C# documentation fixes

- docs/tutorials/basic/go.md
> Fix the broken link of .proto file in Go tutorial

- docs/guides/auth.md
As per https://github.com/grpc/grpc.github.io/issues/162
> First stab at reorganizing auth doc for GA

- docs/tutorials/basic/objective-c.md
Fixes https://github.com/grpc/grpc.github.io/issues/185
> Fixed out of date code snippet

- faq/index.html
Updating user list. More being added soon.
> Adding some new users to who uses gRPC FAQ question

- docs/guides/error.html
- docs/guides/error.md
This is pretty sketchy, particularly the first bit, but I'd like to get some feedback.
> First attempt at error doc

- _data/config.yml
- docs/tutorials/basic/node.md
Updated tutorial to reflect the new static/dynamic code generation options in Node. Will need to wait til the next release to merge though as the links are all to the most recent release, which doesn't have the new examples... (they're in master)
> update tutorial with static/dynamic info

- _layouts/docs.html
- docs/guides/error.md
> removed visible HTML comment

- docs/index.md
heh...to the world that apparently exists outside Google, here's a bone.
> Update Node and Ruby docs.

- docs/tutorials/async/helloasync-cpp.md
Also reformated some lines for length while at it.
Fixes https://github.com/grpc/grpc/issues/5554
@hsaliak FYI
> Added section for async server shutdown in helloworld example

- docs/index.md
- docs/tutorials/basic/csharp.md
https://github.com/grpc/grpc/pull/7008  removes the method, this PR updates the docs.
> Stop referencing NewClient factory method in the docs

- docs/index.md
- docs/tutorials/auth/oauth2-objective-c.md
- docs/tutorials/basic/c.md
- docs/tutorials/basic/csharp.md
- docs/tutorials/basic/node.md
- docs/tutorials/basic/objective-c.md
- docs/tutorials/basic/php.md
- docs/tutorials/basic/python.md
- docs/tutorials/basic/ruby.md
Fixes https://github.com/grpc/grpc/issues/3899 
See also https://github.com/grpc/grpc/pull/7161
> Updated git clone URL

- docs/index.md
- docs/tutorials/basic/python.md
Addresses https://github.com/grpc/grpc/issues/7088
> Updated Python docs to use grpcio-tools instead of raw protoc

- docs/tutorials/basic/go.md
Fixes https://github.com/grpc/grpc.github.io/issues/242
> Fix broken link

- _posts/2016-07-22-vendasta
@LisaFC can you please review and publish. It is ready to go out here.
> Create Vendasta blogpost

- docs/guides/auth.md
Addresses 
https://github.com/grpc/grpc/issues/7548
> Update Python Google auth example to recycle OAuth token

- docs/quickstart/cpp.md
We also need to:
1. Update grpc/INSTALL.md (mention instructions for windows, for instance).
2. Update https://github.com/grpc/grpc/tree/master/examples/cpp/README.md, probably to simply point to this file. Or make it a verbatim copy.
Fixes #237 for C++
> Updated C++ quickstart guide

- docs/quickstarts/java-quickstart.md
> Add Java quickstart

- _sass/base/_markdown.scss
Each commit has useful description
> Prevent lists and h3 from being distracting

- docs/guides/auth.md
- docs/tutorials/basic/go.md
- faq/index.html
> Zinuga patch 1

- faq/index.html
Fixing FAQ formatting and some content
> Fixing FAQs

- _data/config.yml
- docs/quickstart/java.md
- docs/tutorials/basic/java.md
This synchronizes the tutorial with the current state of the examples
and API (since we recently removed some parts of the API). It also
reduces the indentation of code in code blocks to better utilize the
very small column available.
> Update Java tutorial

- _layouts/base.html
PR to add metatag to homepage for domain verification
> Adding meta tag for domain verification. Need for set up of emails.

- docs/guides/auth.md
- docs/guides/concepts.md
- docs/guides/error.md
- docs/guides/index.md
- docs/guides/wire.md
- docs/index.html
- docs/quickstart/csharp.md
- docs/quickstart/index.md
- docs/quickstart/java.md
- docs/quickstart/node.md
- docs/quickstart/objective-c.md
- docs/quickstart/php.md
- docs/quickstart/python.md
- docs/quickstart/ruby.md
- docs/tutorials/auth/oauth2-objective-c.md
- docs/tutorials/basic/c.md
- docs/tutorials/basic/csharp.md
- docs/tutorials/basic/go.md
- docs/tutorials/basic/java.md
- docs/tutorials/basic/node.md
- docs/tutorials/basic/objective-c.md
- docs/tutorials/basic/php.md
- docs/tutorials/basic/python.md
- docs/tutorials/basic/ruby.md
- docs/tutorials/index.md
> Made readable paragraphs <= 80 chars

- docs/quickstart/go.md
> Updated go.md

- docs/tutorials/basic/c.md
- docs/tutorials/basic/csharp.md
- docs/tutorials/basic/go.md
- docs/tutorials/basic/java.md
- docs/tutorials/basic/node.md
- docs/tutorials/basic/objective-c.md
- docs/tutorials/basic/php.md
- docs/tutorials/basic/python.md
- docs/tutorials/basic/ruby.md
Fixes https://github.com/grpc/grpc.github.io/issues/296
> Remove ref to more docs coming soon

- docs/tutorials/basic/c.md
- docs/tutorials/basic/csharp.md
- docs/tutorials/basic/go.md
- docs/tutorials/basic/java.md
- docs/tutorials/basic/node.md
- docs/tutorials/basic/objective-c.md
- docs/tutorials/basic/php.md
- docs/tutorials/basic/python.md
- docs/tutorials/basic/ruby.md
Fixes https://github.com/grpc/grpc.github.io/issues/296
> Remove reference to more docs coming soon

- docs/quickstart/go.md
- docs/tutorials/basic/go.md
Updated quickstart and tutorial following friction log
> Update go quickstart and tutorial

- community/index.html
- docs/samples/index.html
- docs/samples/index.md
Adding a set of samples in doc 
Adding reference to gRPC Ecosystem in Community pages
> Adding samples and adding reference to gRPC Ecosystem under Community

- contribute/index.html
Fixing contribution guidelines doc
> Changing contribution guidelines doc

- docs/tutorials/basic/android.md
> Add android routeguide tutorial

- docs/quickstart/csharp.md
- docs/tutorials/basic/csharp.md
This fixes some rendering issues that could be seen when using jekyll. 
It also makes a few of typo and improvement tweaks.
> fix C# rendering issues found on jekyll

- about/index.html
- docs/index.html
- faq/index.html
Fixing:
about: PHP caveat
docs: gRPC other projects
faq: adding sign up for web etc
> Making some more changes to docs and about

- docs/tutorials/basic/android.md
I tried to shorten the links. They were really, really long and ugly. Now one is just semi-long and ugly.
> Improve formatting and links in Android tutorial

- _includes/doc-side-guides-nav.html
- _includes/footer.html
- about/index.html
- docs/guides/benchmarking.md
- Fixed benchmarking to read 'Benchmarking' instead of 'gRPC Performance Benchmarking'
- Update logo links.
- Point Overview to the right place
> Minor, cosmetic fixes post GA merge.

- _includes/doc-side-quickstart-nav.html
> Add android quickstart

- docs/index.html
> Add android as a language in the docs section.

- _posts/2016-08-23-gablog.md
- about/index.html
Blogpost for 1.0 launch tomorrow. Will be made live tomorrow morning.
> Adding 1.0 blogpost

- docs/quickstart/php.md
> Add note for `rake` & `ronn` commands.

- _posts/2016-08-29-vendasta.md
> Adding vendasta blog

- docs/tutorials/basic/android.md
- docs/tutorials/basic/csharp.md
- docs/tutorials/basic/java.md
- docs/tutorials/basic/node.md
- docs/tutorials/basic/ruby.md
> fix wrong spelling

- _posts/2016-09-06-vsco.md
> Adding VSCO blogpost

- docs/quickstart/php.md
add zlib1g-dev as a dependency
add `npm install` for instructions to running the node package
Fix typo with "proto-gen-php"
> Fix minor errorss

- _sass/base/_colors.scss
- _sass/base/_markdown.scss
- _sass/base/_override.scss
- _sass/base/_text.scss
Darker text colours, bigger line spacing.
Fixes (hopefully?) https://github.com/grpc/grpc.github.io/issues/354
Google folks on our network can see a preview at http://lcarey0-l.dub.corp.google.com:4000/grpc.github.io/docs/, PTAL.
> Accessibility changes to styling

- faq/index.html
Users should see the non-edit link for the form
> Remove editable link

- _posts/2016-09-06-bazel-rules-protobuf.md
Contributes blog post to grpc.io website.  Closes https://github.com/pubref/rules_protobuf/issues/5.  
I chose the filename with date Sept. 6, which is the Tuesday after labor day.  Let me know if this is an acceptable time frame for the post.
Thanks!
> Bazel rules protobuf

- docs/guides/auth.md
> Fix small typo in auth documentation

- _posts/2016-10-13-bazel-rules-protobuf.md
Paragraph 1.6 is not rendering properly due to the lack of on empty line in the md file.
> Fix paragraph render bug

- _sass/base/_markdown.scss
- _sass/base/_override.scss
Realized many formatting oddities were due to not having CSS for ordered lists....
> Formatting fixes

- community/index.html
A subreddit dedicated to gRPC has been created, you may find the proposal [here](https://www.reddit.com/r/golang/comments/5f5yj8/a_grpc_specific_subreddit/).
Subreddit link: https://www.reddit.com/r/grpc/
> Update community page, add Reddit link.

- docs/guides/wire.md
Looks like I forgot the quotes in #404.
> Fix ABNF notation.  Add note about path format.

- docs/quickstart/php.md
> Added closing code block.

- docs/quickstart/php.md
Fixes #436 
Fixes #437 
Fixes #431
> PHP: Update quickstart guide

- about/index.html
> Update C# supported platform list

- docs/quickstart/cpp.md
> Add details to cpp quickstart

- docs/quickstart/php.md
> PHP: update instructions for CentOS/RHEL users

- docs/tutorials/basic/ruby.md
I'm pretty sure you don't mean python. Also, I'm pretty sure you mean to link to quickstart - not installation, which isn't a thing.
> Small fixes for ruby docs

- docs/guides/auth.md
Bulleted list wasn't formatting properly with Jekyll's markdown engine
> fix wonky bullets

- _posts/helm-grpc.md
> Helm & the gRPC Experience

- docs/generated/go.md
- docs/index.html
- docs/reference/go/go.md
This is a rough draft right now and I'm planning to do some more polishing.
cc @hsaliak @dfawley @ericgribkoff  if the general direction of this looks ok.
> Doc on Go generated code

- _sass/pages/_blog.scss
- blog/index.html
- js/common.js
Main blog page was looking very messy, I've fixed some headings and styles and it now looks a bit more normal...
> Fix blog styles

- docs/reference/go/generated-code.md
> fix format issue

- docs/tutorials/basic/go.md
Hi *, 
this is my first contribution. I hope it's appreciated and I can continue. 
Not hoping there are more mistakes ;-)
Greets Stefan
> Correcting a simple mistake, i.e. a double 'the'

- docs/quickstart/node.md
> Update minimum required Node.js version

- docs/guides/auth.md
Fixes
https://github.com/grpc/grpc/issues/8621
https://github.com/grpc/grpc/issues/6860
> Switch to google-auth-library-python in example

- _data/config.yml
- docs/quickstart/csharp.md
- docs/quickstart/objective-c.md
- docs/quickstart/php.md
- docs/quickstart/python.md
- docs/quickstart/ruby.md
Fixes issue mentioned in https://github.com/grpc/grpc/issues/11426.
> Clone examples for wrapped langs from the current release branch.

- docs/guides/benchmarking.md
> Suggest how to benchmark PHP and mobile

- _posts/2016-09-06-vsco.md
- _posts/2017-04-12-yikyak.md
- _posts/2017-05-15-helm-grpc.md
Excerpt markers so we don't get entire blog posts on the landing page
> More blog fixes

- docs/quickstart/go.md
Edited the protoc command to address the example folder structure.
> Updating protoc cmd as per example folder structure

- docs/quickstart/ruby.md
`lib/helloworld_services.rb` => `lib/helloworld_services_pb.rb`
> Fix generated file name

- docs/index.html
- docs/reference/java/generated-code.md
opensourced the internal java codegen guide
resolves #508
> Create generated-code.md for java

- _data/config.yml
This should have been done 4-5 weeks ago, but was forgotten.
> Bump version of grpc-java

- docs/index.html
- docs/reference/index.html
API reference updated here: https://github.com/grpc/grpc/pull/12348
> P1: Fix links to C# API reference

- _posts/2017-09-14-meetup-kit.html
https://github.com/grpc-ecosystem/meetup-kit
> Blog post for the Meetup Kit

- docs/tutorials/basic/c.md
- CreateChannel does not accept ChannelArguments
- Adds reference to CreateCustomChannel to specify ChannelArguments
> c.md - Fix erroneous use of CreateChannel

- docs/tutorials/basic/node.md
> Update code in Node basic tutorial to match example code

- docs/index.html
Fixes https://github.com/grpc/grpc.github.io/issues/582.
> Fix zipkin link

- docs/guides/index.md
Fixes https://github.com/grpc/grpc.github.io/issues/438 and updates the wording of the docs a bit.
> Add link to protobuf reference

- _sass/base/_markdown.scss
Fixes #447
Attractively modelled by my copy here: https://lisafc.github.io/grpc.github.io/docs/guides/auth.html
> Made font style slightly heavier

- _sass/base/_override.scss
...otherwise it's now lighter-weight than para text
> Quick follow-up to change weight of link text

- docs/quickstart/node.md
Per @murgatroid99 comments. Closes issue #584.
> Update Node Version (Documentation Fix)

- docs/tutorials/basic/csharp.md
two(2) [protocol buffers] links fixed
> Fix: Some links fixed

- docs/quickstart/cpp.md
Fixes https://github.com/grpc/grpc/issues/12422
> Simplify and clarify the instructions for C++ example

- community/index.html
It fixes all the issue links on the community page.
> Fix issue links on community page.

- _data/config.yml
> Update config.yml for Java 1.9.0 release

- docs/tutorials/basic/c.md
InsecureCredentials() is now InsecureChannelCredentials()
> fix example code in the documentation

- docs/guides/error.md
Add link to https://github.com/avinassh/grpc-errors in errors.md
> add link to grpc-errors repo

- _posts/2018-01-26-grpc-and-deadlines.md
Publish the deadlines blog post so it's visible.
> Publish the deadlines blog post.

- _posts/2018-03-06-so-you-want-to-optimize-grpc-part-1.md
> Optimization blog post

- docs/guides/auth.md
Fixes https://github.com/grpc/grpc-go/issues/1396
Fixes https://github.com/grpc/grpc.github.io/issues/545
/cc @dfawley
> Add Go examples to auth guide

- _layouts/post.html
> include author link on blog post

- _posts/2018-03-06-so-you-want-to-optimize-grpc-part-1.md
@LisaFC FYI.
I would love to know if this works, but I have no way to preview the change.
> try out author link, and remove extra header

- docs/guides/auth.md
fixes https://github.com/grpc/grpc-go/issues/1980
> fix go cert example

- _posts/2018-03-06-so-you-want-to-optimize-grpc-part-1.md
- _posts/2018-04-16-so-you-want-to-optimize-grpc-part-2.md
@hsaliak and @LisaFC  FYI
cc @ncteisen
> Optimization blog Part2

- about/index.html
Go minimum required version is 1.6.
> update go dep listed in about page

- _posts/2018-02-26-grpc-and-deadlines.md
- Missing bracket
- codepb.CANCELED -> status.Canceled
> small go post fixes

- docs/guides/auth.md
I have added some helpful insights to the existing Java documentation
> Added minor details regarding SSL/TLS authentication

- docs/quickstart/android.md
In response to https://github.com/grpc/grpc-java/issues/4407
cc @ejona86
> Note that gRPC Java Android servers are not supported

- _posts/2018-06-19-kotlin-project-setup.md
Add property to make the image not take up the entire screen (hopefully).
> kotlin post: fixed size image, update title

- _posts/2018-06-19-kotlin-project-setup.md
> undo image resize attempt

- _posts/2018-06-19-kotlin-project-setup.md
> kotlin post: resize image with kramdown

- docs/guides/benchmarking.md
> Publish CHTTP2 microbenchmarks

- _sass/base/_colors.scss
> make text color darker for better visibiity

- _posts/2018-06-26-gracefully_clean_up_in_grpc_junit_tests.md
also add missing `throws` in one of the code snippets.
> Remove backslash as it is not rendered correctly

- docs/tutorials/basic/node.md
Duplicate of #659 and #700  but without waiting for CLA signing.
> fix node js example

- docs/guides/benchmarking.md
> Update benchmark proto links

- _data/config.yml
> bump core to 1.14.1

- docs/tutorials/basic/python.md
Add note about pb2 naming in Python.
> Add note about pb2 naming in Python.

- _posts/2018-08-14-take-the-grpc-survey.md
Folks, could i please get a review of the survey blog post?
> Add blog for grpc-survey

- _posts/2018-10-23-grpc-web-ga.md
Update wording on what GA means, since this was pointed out in public forums.
> Update wording to clarify what GA means.

- docs/tutorials/basic/csharp.md
Closes #751 
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>
> Fix typo in C# Basic Tutorial

- _posts/2018-06-19-kotlin-project-setup.md
- _posts/2018-07-13-http2_smarter_at_scale.md
- _posts/2018-08-20-grpc-on-http2.md
Per @carl-mastrangelo's https://github.com/grpc/grpc.github.io/pull/775#discussion_r233095925
> Add a new line between the ---, since the GitHub MD parser is wonky.
Fixing 3 affected files.
> Add empty lines strategically to keep wonky parser happy

- docs/quickstart/web.md
> Fix grpc-web quickstart

- _data/config.yml
> bump core to 1.17.1

- _posts/2018-18-18-grpc-dotnet-build.md
Looks like a table now: https://github.com/kkm000/grpc.github.io/blob/9270535dedf73da44a66cb3d2d8d37d5cf1e7af3/_posts/2018-18-18-grpc-dotnet-build.md
> Add quotes around title because ':'

- docs/tutorials/basic/java.md
> Fix spelling error.

- docs/quickstart/csharp.md
- docs/tutorials/basic/csharp.md
Followup for example updates in https://github.com/grpc/grpc/pull/14684.
> update C# docs with Grpc.Tools automatic codegen

- _includes/footer.html
> Update year in the site's footer copyright

- docs/tutorials/basic/web.md
I just fixed a typo in sample code.
> Fix syntax error of gRPC Web client sample code

- _data/config.yml
> Core version bump to 1.19.0

- docs/index.html
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>
> etcd is not a CoreOS project anymore

- _includes/hero.html
This PR removes the banner added for gRPC Conf. Don't merge until after the conf 😄
> Remove gRPC Conf banner

- _data/config.yml
> Update grpc-java version referenced by tutorials to 1.20.0

- _data/config.yml
> Bump gRPC version to v1.20.0

- _layouts/base.html
> Update analytics ID

- _layouts/base.html
- robots.txt
> Disallow robots and indexing of any pages

- robots.txt
Closes https://github.com/grpc/grpc.io/issues/612
> Allow indexing of API docs hosted from grpc/grpc
