grpc/grpc.github.io

docs/guides/auth.md, docs/tutorials/basic/csharp.md
Update C# to the new auth API coming in 0.12 release.
This should be enough to address C# portion of https://github.com/grpc/grpc/issues/4243.
@jboeuf  for sanity check. Besides JWT, I decided to cover also OAuth2 and  per-rpc cases, because they might come handy.
=> Update C# docs for the new auth API.

docs/guides/auth.md
The Markdown engine on [the website](http://www.grpc.io/docs/guides/auth.html#authenticating-with-google-c) expects an extra new-line after the bold subtitles (I guess). So, I changed them to h4 instead.
=> Header4 instead of bold titles

docs/guides/auth.md
- Changing JWT Access to a more general "Scopeless credentials" for the
recommended approach to authenticate to Google.
=> Google default credentials may or may not be JWT Access.

docs/guides/auth.md
=> Add Python auth example

docs/reference/index.html
By default, if no version is given, the link will go to the latest published version, which is what we always want.
=> Remove version specifier from Ruby reference docs link

index.html
The link currently points to [/posts/principles/](http://www.grpc.io/posts/principles/) which returns returns 404
The correct link seems to be [/posts/principles](http://www.grpc.io/posts/principles) (no trailing slash).
=> Fix link to Design Motivations & Principles

docs/index.md
The current code fails at runtime.
```
2016/02/22 18:03:47 did not connect: grpc: no transport security set
(use grpc.WithInsecure() explicitly or set credentials)
```
I think it's better to avoid this error and point to the authentication
docs.
=> Add grpc.WithInsecure in Go sample

docs/tutorials/basic/csharp.md
Trying to do this myself it failed. I noticed that the Windows command included the plugin name before the location of the plugin executable.
=> Fix C# non-Windows `protoc` plugin argument

docs/guides/auth.md, docs/index.md
Added per-language installation instructions (either one-liners where available or links to installation docs) for gRPC and protoc to the overview. Am missing some details for protocol buffers in Python and Ruby....
=> Updated installation instructions

docs/tutorials/basic/python.md
Hey 👋 
I was going through the gRPC Basics - Python tutorial and noticed that the link for setup instruction in the quickstart guide was pointing to http://www.grpc.io/docs/installation/python.html which doesn't seem to exist.
I've changed this to point to https://github.com/grpc/grpc/tree/master/examples/python which I believe to contain the intended information?
Thanks,
.FxN
=> Fixing broken Quick start link

docs/tutorials/basic/java.md
This fixes an inconsistency (caused by me) due to half-updating the docs
in commit 9368475.
bindService is not necessary when extending AbstractRouteGuide instead
of implementing RouteGuide. Using AbstractRouteGuide is becoming the
preferred method, but for now we just want fix the current method.
Fixes grpc/grpc-java#1850
=> tutorial/java: Call bindService

docs/guides/auth.md
- Removing legacy way to authenticate with Google.
- Java and Python will need to update their examples to use "scopeless"
creds.
- Fixes #180.
=> Google authentication cleanup.

docs/guides/concepts.md, docs/index.md, docs/tutorials/basic/csharp.md
Adjust the gRPC documentation to make sure C# users won't be confused by the term "stub" (in C# the idiomatic term is "client"). I went through all our docs and updated all places that could cause confusion.
Fixes https://github.com/grpc/grpc/issues/6988
=> Fix confusion caused by terms "client" and "stub".

release
In order to get the branch name for the current release. This will be used throughout tutorials and examples where checking out a specific branch is better than working at HEAD. For example
```
$ git clone -b $(curl http://grpc.io/release) github.com/grpc/grpc
```
=> Added "release" URL

docs/guides/auth.md
For #181
This requires grpc-java 0.15, which is not yet released.
=> Swap Java auth to scopeless credentials

docs/index.md, docs/tutorials/basic/java.md
- Interfaces in the proto generated code are deprecated, should not be in the example.
- static bindService method is deprecated, should not be in the example.
=> Update java guide/tutorial to v0.15.0

docs/tutorials/basic/java.md
Remove extra tag from markdown that breaks rendering of Heading 2. 
Same as #248 and #266 but for the Java tutorial.
=> Fix markdown rendering in Java tutorial

docs/tutorials/basic/python.md
Remove extra tag from markdown that breaks rendering of Heading 2. 
Same as #248 but for the Python tutorial.
**Before:**
**After:**
=> Fix markdown rendering in Python tutorial

docs/guides/concepts.md
The "Deadlines" header is not rendered correctly on the live grpc.io
site [0]. This is almost certainly due to the manually-inserted anchor
tag immediately preceding it.
Since the anchor tag in question matches the heading text, it can be
removed entirely rather than moved to the start of the following
paragraph. The fixed heading will have its own automatically-generated
anchor tag with the same name.
[0] http://www.grpc.io/docs/guides/concepts.html#deadlines
=> Remove extraneous anchor tag that breaks rendering

docs/quickstart/cpp.md
Changes needed to display quickstarts correctly. 
Tested on local jekyll instance, confirmed that syntax highlighting works as expected and side-navigation/justification works. 
Completes changes related to #237 for C++.
/cc @LisaFC
=> Fix quickstart formatting

_sass/base/_override.scss, _sass/pages/_docs.scss
Line-wrapped code looks horrible; just displaying a scroll bar is much
better when possible.
Headers could previously overlap with the scroll bar of code which would
prevent scrolling. This was to create a larger clickable area for
headers. However, the clickable area was much larger than it needed to
be, and simply reducing the area produces apparently-identical results
without breaking scrolling for code snippets.
=> Don't line-wrap code snippets

docs/quickstarts/csharp-quickstart.md
Here is a csharp quickstart. Walked through it on windows Visual Studio 2015, Mac OS X, and linux. Did run into issues generating the protos files, which this related PR should fix: #7514, but otherwise it seemed to work.
Followed the python template but made some tweaks for C#.
Got most of this right from http://www.grpc.io/docs/tutorials/basic/csharp.html#generating-client-and-server-code, https://github.com/grpc/grpc/tree/master/examples/csharp/helloworld, and https://github.com/grpc/grpc/blob/master/src/csharp/README.md.
This PR previously was made on wrong branch (https://github.com/grpc/grpc/pull/7515).
=> added csharp quickstart doc

docs/quickstart/node.md, docs/quickstart/php.md, docs/quickstart/python.md, docs/quickstart/ruby.md, docs/tutorials/basic/c.md, docs/tutorials/basic/csharp.md, docs/tutorials/basic/go.md, docs/tutorials/basic/node.md, docs/tutorials/basic/objective-c.md, docs/tutorials/basic/php.md, docs/tutorials/basic/python.md, docs/tutorials/basic/ruby.md
The new website doesn't have as much vertical space. We don't want to
waste that space on avoidable indentation.
Note for reviewers: this change only includes whitespace changes, as verified with `git diff -w`
=> Remove unnecessary indentation in code snippets

community/index.html
Using mailto: to a mailing list via a link that says "Join the mailing
list" seems like a sure way to get people to send an email with
"subscribe" as the subject. Upon reflection, we've decided we don't want
that.
=> Change mailing list link to a URL to Google Groups

community/index.html
It looks a bit ugly, because there's a ton of the "external link" icons
without any left margin, but this is better than it was.
=> Link shortcuts on community page to actual pages

docs/tutorials/basic/ruby.md
Note I skipped the ```&``` because it suggests using 2 terminals.
=> Fix route_guide ruby example

docs/tutorials/basic/csharp.md
Left out this basics doc earlier, I think its short instructions on building the example at the end should refer to the quickstart instructions because of the issues with nuget, Xamarin Studio, and Monodevelop.
=> update basics with link to quickstart for ide issues

docs/quickstart/python.md
Used the suggested fix from here:
https://github.com/pypa/pip/issues/3165
=> Add Python OSX El Capitan installation workaround

docs/quickstart/cpp.md, docs/quickstart/csharp.md, docs/quickstart/node.md, docs/quickstart/objective-c.md, docs/quickstart/php.md, docs/quickstart/python.md
The directory in the grpc repo is `examples/protos`, not `examples/proto`.
=> Fix file path of helloworld.proto

docs/quickstart/csharp.md, docs/tutorials/basic/csharp.md
Addressing issues from the friction log, including updates to the Grpc.Tools version in code gen commands, and making the pre-reqs more clear.
@ejona86, tried here to reword the pre-req notes here to make the use of .NET Core SDK, Mono, and Nuget more clear. Also I wasn't sure on what the issues with code snippets not showing correctly in the Run grpc sections, as I was able to see them, but this adds new lines before those snippets as I'd seen elsewhere.
=> Address issues in friction log and make pre-req notes more clear.

docs/quickstart/csharp.md
this simplifies the shell commands to generate protos code in the quickstart. it also changes the old "nuget install Grpc.Tools" command, which I found to not be working on all platforms, or with different versions of nuget.
=> simplify code gen commands in csharp quickstart

docs/quickstart/python.md
- Explicit instructions for upgrading pip
- Unify windows/unix pip usage
This should help to avoid accidental source installation now that we have binaries for all supported platforms.  
cc @nathanielmanistaatgoogle 
Note the virtualenv workaround is specifically for goobuntu where python-pip comes installed and prevents an easy upgrade of pip.
=> Simplify pip instructions in Python Quickstart

docs/quickstart/csharp.md, docs/tutorials/basic/csharp.md
helloworld and routeguide c# examples have pending changes not included in the v1.0.0 release (https://github.com/grpc/grpc/pull/7720). After https://github.com/grpc/grpc/pull/7720 is merged, the v1.0.x branch examples, rather than the v1.0.0 examples, should be correct.
=> clone v1.0.x branch in csharp examples

_includes/doc-call.html
Add android java to the main page, follow up to #347 to ensure consistency. 
I also re-ordered the list of languages so that both pages are consistent. 
/cc @a11r
=> adding android java to the main page

faq/index.html
The question "Can I use it in the browser?" appears twice with similar
answers in the FAQ page. Remove one occurrence by keeping what appears
to be the most complete answer.
See the preserved question [here](https://github.com/icecrime/grpc.github.io/blob/59de19cac272024368da21dd8f417f0581a2db8f/faq/index.html#L94-L99).
Signed-off-by: Arnaud Porterie (icecrime) <arnaud.porterie@docker.com>
=> Remove duplicated FAQ entry

docs/tutorials/basic/go.md
Link wasn't rendering correctly due to a line break between ending `]` and starting `(`.
=> Fixing markdown link

docs/quickstart/csharp.md
I found that on Linux, if I didn't update NuGet via `nuget update -self`, then I wouldn't get the linux packages.
=> Note that you may have to update NuGet

docs/quickstart/php.md
I missed that I needed protoc for Protobuf-PHP, so added a section (copy-paste from the Go quickstart) to outline how to install it, and make it more visible that it is required.
=> Add section on installing protoc

docs/guides/error.md
Reading http://www.grpc.io/docs/guides/error.html it was clear that this segment had been mangled by an edit.  Reverting it to state before change: https://github.com/grpc/grpc.github.io/commit/076c9c1e351bd099394e7cf557451682f72896df#diff-43cc74a26b167e70dcecef7f8857ad94L38
=> Fix formatting of Network Failures table

docs/tutorials/basic/go.md
The two streaming examples had their markdown header lines inadvertently combined with the first sentence of the following body text. This fixes the two cases I found.
Here's what this looked like before:
=> [docs][go]: Fix section headers inadvertently combined w/ body

_data/config.yml
Just tested the quickstart with 1.0.0 and it worked perfectly - figured it made sense to update it to 1.0.0
=> Update java release property 1.0.0

docs/quickstart/go.md
As I found there is a typo in the quickstart/go.md where it has referred HelloReply as HelloResponse. This pull request has fixed that. Thanks!
=> Fixing typo HelloResponse in quickstart/go.md

docs/quickstart/csharp.md
So indeed it looks like the latest releases of mono and Xamarin Studio update nuget to 2.12.
I guess it's noted in the 4.4.2 and 6.0 release notes for each btw.
For the actual issue with Grpc.Tools and nuget 2.12, filed https://github.com/NuGet/Home/issues/3427#issuecomment-246019865. To work around it, the workaround in this change can work without using nuget, though it might be more involved than desired...
=> remove nuget update -self suggestion after mono update

docs/tutorials/basic/go.md
Inserted a single quotation mark (') between "`RouteGuide_RecordRouteServer`" and "s".
=> Fixed a typo in the "gRPC Basics - Go" page

docs/quickstart/python.md
Since the documentation doesn't cover writing a python script for code generation anywhere else, I thought it would be good to show how to manually regenerate the code from the .proto file as well - so that it was clear what was happening.
=> Add example of regenerating code via python -m grpc.tools.protoc

docs/quickstart/go.md
Protoc download link is not formatted as a link. I changed it into a link to provide better readability.
=> Updated go.md for protoc link

docs/guides/wire.md
As we discussed a couple of weeks ago.  Needed for grpc/grpc#7818.
=> Document that path must be of the same format, regardless of IDL.

docs/tutorials/basic/node.md
`grpc.Credentials` should be `grpc.credentials` in grpc.
=> Fix typo in grpc node guide.

docs/tutorials/basic/java.md
Sections are messed up in documentation due to formatting issues.
=> Fix typos in Java documentation

docs/quickstart/python.md
The grpc.tools.protoc generation tool command was wrong. This commit fixes that.
See https://github.com/grpc/grpc/issues/8738 for more details.
=> Fix bug in "Generate gRPC code"

docs/tutorials/basic/go.md
Previously sent to https://github.com/grpc/grpc-go/pull/972, but that seems to not be this website, but a fork of this tutorial.
The actual broken link on the website is on this page:
http://www.grpc.io/docs/tutorials/basic/go.html#defining-the-service
=> Correct broken markdown

docs/quickstart/csharp.md
Use same syntax and convention as docs/tutorials/basic/csharp.md
Fix 'packages' is not recognized as an internal or external command, operable program or batch file.
=> Fix protoc command on Windows 10

docs/tutorials/basic/ruby.md
Hi,
This fixes the confusing example. It didn't specify what kind `port` has. My first though was that is was an int:
``` ruby
s = GRPC::RpcServer.new
s.add_http2_port(8765, :this_port_is_insecure)
=> TypeError:
no implicit conversion of Fixnum into String
```
Then, I tried as string:
``` ruby
s = GRPC::RpcServer.new
s.add_http2_port("8765", :this_port_is_insecure)
=> RuntimeError:
could not add port 8765 to server, not sure why
```
Finally it worked with address string
``` ruby
s = GRPC::RpcServer.new
s.add_http2_port(":8765", :this_port_is_insecure)
```
=> Fix example for ruby server

_sass/base/_override.scss
Fixes some display issues with lists on the [/about](http://www.grpc.io/about/) page.
=> force list-nested p tags to have inline display

docs/tutorials/basic/c.md
Jekyll requires two newlines before list items (http://stackoverflow.com/a/30168224/391865).
Here is how [it](www.grpc.io/docs/tutorials/basic/c.html#generating-client-and-server-code) looks now:
=> fix list formatting

docs/tutorials/basic/c.md
A service should be implemented in a thread-safe way. A comment on the thread safety of the example service has been added.
=> Document thread-safety of a service

docs/index.html, docs/quickstart/php.md, docs/reference/index.html
I re-generated the PHP API docs with a different doc generator and need to update the website's links to these reference docs
=> PHP: update reference docs links

docs/guides/benchmarking.md
CC @adelez, @matt-kwong, @apolcyn,
=> Add link to "latest_release" perf dashboard

_layouts/base.html
This has two main benefits:
1.  The tracking snippet needs to be in <head> in order to use
Google Search Console, which is the only way to see what
search terms ended up directing users to grpc.io.  Without it,
the search query shows up as the infamous "(not provided)".
2.  Page loads are faster.  The [analytics][1] page suggests
putting it in the <head>.  Also, it suggests page loads are
faster if using a modern browser.  Checkout our Google
Analytics for grpc.io shows an overwhelming number of users
with Chrome, Firefox, Safari.  For IE users (a small percent),
most are using version 11 which supports async js.
[1]: https://developers.google.com/analytics/devguides/collection/analyticsjs/
cc: @LisaFC
=> Move tracking snippet to top of page and load async

docs/guides/auth.md
The comment does say "using the credentials created in the previous step," but I think it's still better using the same variable name.
=> Use defined variable in C++ auth example

docs/guides/concepts.md
You can always cancel from another thread ("racily"), cancel before invoking the RPC, or in the case of streaming synchronous RPCs, cancel in between stream ops.
=> Remove incorrect text about canceling a synchronous RPC

docs/guides/concepts.md
In particular it is no longer the case that a timeout must be specified when invoking an RPC with gRPC Python.
=> Correct deadlines/timeouts text

_data/config.yml
Our guides often ask the user to issue a git
clone command which checkouts a branch specified
in grpc.io/release URL.  It is critical that the
release version gets updated as we ship new
versions. This patch bumps it from 1.0.0 to
1.2.0.
(c.f. https://github.com/grpc/grpc.github.io/issues/471)
=> Bump the grpc release version to v1.2.0

_sass/base/_markdown.scss, _sass/pages/_about.scss, docs/quickstart/android.md, docs/quickstart/cpp.md, docs/quickstart/csharp.md, docs/quickstart/go.md, docs/quickstart/java.md, docs/quickstart/node.md, docs/quickstart/objective-c.md, docs/quickstart/php.md, docs/quickstart/python.md, docs/quickstart/ruby.md
Quickstarts: added and/or fixed the What's Next sections so they point to actual docs rather than just the doc overview page (I think the overview page's URL originally had something useful on it)
CSS: small fixes to our styling for lists so we don't keep ending up with lists with the bullets on different lines to the text. I *think* this works...
=> Some minor fixes

_data/config.yml
Updates the latest release pointer to 1.3.
(Should be merged after release is made.)
=> Update grpc.io/release to 1.3.0

docs/quickstart/java.md
Changes return type HelloResponse to HelloReply in the description of the helloworld.proto definition.
The description states:
> For now all you need to know is that both the server and the client "stub" have a `SayHello` RPC
> method that takes a `HelloRequest` parameter from the client and returns a `HelloResponse` 
> from the server, and that this method is defined like this:
> 
> // The greeting service definition.
> service Greeter {
>     // Sends a greeting
>     rpc SayHello (HelloRequest) returns (HelloReply) {}
> }
so I think the SayHello RPC method returns a HelloReply from the server.
=> Changes type reference in description

docs/tutorials/basic/c.md
Currently you can see the raw markdown and URL at http://www.grpc.io/docs/tutorials/basic/c.html#defining-the-service
=> Remove space that was breaking a link

_data/config.yml
Updating slipped `/release`
We need a better way to ensure tagging releases are followed by this version bump.
=> Bump /release to 1.3.2

docs/quickstart/android.md
This adds instructions for connecting the client app running on an Android physical or virtual device to the server running on their local machine. This should help anyone following the quickstart guide, as it's not obvious what to enter for the host/port on the client app unless you have previous experience with android.
cc @makdharma
=> Add details on connecting to server from Android device/emulator

docs/tutorials/basic/ruby.md
This provides the fix described in https://github.com/grpc/grpc.github.io/pull/501.
(the json file needs to be passed as an arg - added a comment)
=> Fix ruby tutorial example runs

docs/quickstart/php.md
This is to update the PHP quickstart guide after we de-coupled the protobuf runtime library from our composer package.
FYI @betterbrent
=> PHP: Update protobuf runtime library instructions

_config.yml, _posts/2017-06-15-grpc-load-balancing.md, blog/index.html
Add proper heading material to blog post, make sure Kramdown can read Markdown inside HTML elements, ensure we get proper excerpts on blog landing page, fix blog landing page toc
=> Blog formatting fixes

CNAME
Serve the contents from a clean `grpc.io` URL and drop the redirect to `www`.
=> Drop www from grpc.io

_posts/2017-08-17-community-meeting-update.md
Brought this up to April briefly about publishing a brief synopsis of the weekly meeting notes as a blog post. I rolled this up into 4 major sections: General Announcements, Release Updates, Platform Updates, and Language Updates. I'm working on back-porting notes from the first meeting, but that one had a lot more going on.
Let me know if there are any changes that need to be made.
CLA submitted
=> Added community meeting notes blog post from 8/17

_posts/2017-08-17-community-meeting-update.md
Minor cosmetic change to make blog headings work correctly.
=> Add more link to community meeting blog post so that the headings are not corrupted

docs/index.html
TiDB is also using gRPC, thus adding the link to it.
=> Add a link to TiDB which also uses gPRC

docs/reference/index.html
Seems like Ruby docs are accessible at HTTP instead of HTTPS -- same as here:
https://grpc.io/docs/
🙇
=> Fix link to Ruby docs

docs/quickstart/ruby.md, docs/reference/index.html
https doesn't seem to work with rubydoc.info ATM
=> fix broken rubydoc links

docs/quickstart/go.md
Some updates have to be done on the http2 package when trying to compile grpc. Since the compilation fail if http2 package is not up-to-date, the `update` option should be passed to go get.
=> Add -u flag to go get grpc

community/index.html
The Meetups haven't been happening in over a year, whereas the Community
Meeting has been quite regular.
=> Replace Meetup information with Community Meeting

docs/quickstart/php.md, docs/tutorials/basic/php.md
1. To solve the issue https://github.com/grpc/grpc/issues/12481 alone with https://github.com/grpc/grpc/issues/13193 : 
Installation instruction should be consistent between grpc, grpc.io while it needs to notify the compatibility between grpc version and protobuf version.
2. To solve the issue https://github.com/grpc/grpc/issues/12229 : update how to run examples.
For 1:
By referring to the grpc/src/php/readme.md, adding installation guidance missed in grpc.io.
- Update installation commands for Pre-request: php, pecl, composer, phpunit.
- Update install grpc extension by pecl and and add installation method by build from source.
- Update other pre-request related to protobuf: Install protoc, protobuf.so and build grpc_php_plugin.
- Add compatibility table between grpc version and …
=> gRPC PHP: update quickstart and tutorials

docs/tutorials/basic/android.md
Otherwise the example won't build, because it references SNAPSHOT
versions.
=> Fix Android tutorial to check out release tag

docs/quickstart/objective-c.md
Specify gRPC minimum deployment iOS version in quick start.
=> Specify gRPC minimum deployment version

_data/config.yml
Should be merged only after https://github.com/grpc/grpc/pull/14545 is merged
=> Bump /release to 1.10.0 #glamorous

docs/tutorials/basic/java.md
It's been stable for years.
Fixes #656
=> tutorials/basic/java: proto3 is stable

_includes/footer.html
Because Google owns the google.io domain, legal says that we need to add a link to the privacy policy in our site.
=> Add privacy policy link to footer

_sass/base/_common.scss
When clicking on text that has the default text cursor, I don't expect the page to scroll. Changing the cursor to a pointer for this clickable-header class would provide a better user experience.
=> Different cursor for clickable-header class

docs/tutorials/basic/node.md
This proto loader library is now the recommended way to load `.proto` files with Node gRPC, and this change matches the changes to the examples themselves in grpc/grpc#15239.
=> Update Node proto loading example with new loader library

docs/guides/index.md
It's nice to define acronyms on first use, especially on getting started docs.
=> Define the IDL acronym on first use.

docs/quickstart/python.md, docs/tutorials/basic/python.md
After generating relevant server/client code for python, the presence of
```python
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
```
causes,
```bash
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
ImportError: No module named api
```
`pip install grpcio-tools` only brings in `google/protobuf` module.
Installing `googleapis-common-protos` causes the required files, specifically, 
`google/api/annotations_pb2.py` to be pulled in, thus resolving the import error.
There are examples like [python-grpc-hack.sh](https://github.com/kasey/grpc-example/blob/master/installers/python-grpc-hack.sh) out there, which is basically hacking
around the absence of the required module. I have not yet tried the Java codegen yet
but till the relevant …
=> Update to account for import error in generated python code

docs/quickstart/cpp.md
Changing to BUILDING.md because INSTALL.md was renamed to it in f389e5267afe7a7f735fd7e4c2f923640d2f72c5.
=> Fix link to build docs

_layouts/base.html
All pages ought to have a unique title. For several pages, no title is specified.
For all those pages, a headline is specified. 
Thus, falling back to a headline when a title does not exist fixes this problem.
=> Ensure all pages have a unique title

docs/tutorials/basic/python.md
Currently, the Overview links go to the docs overview page, not the grpc overview.  This isn't very helpful to a new reader, and it took me a minute to find the actual grpc overview from the index page.
If this is accepted a similar change to other languages would probably be beneficial.
=> Make overview links helpful

docs/quickstart/go.md
Context "ctx" instance has been previously instantiated in the same "client" file. Reusing the same instance will reflect a consistent example across all client code.
=> Trivial: reuse the already-defined context instance

docs/quickstart/cpp.md
Starting from scratch and following all proposed steps on Linux leads to an incomplete setup: it's missing the install command for gRPC compiled from source.
I've added it in the main C++ quick start document.
=> Update installation instructions in C++ quickstart.

_posts/2016-4-4-installation.md, docs/tutorials/basic/c.md, docs/tutorials/basic/ruby.md
Follow up for https://github.com/grpc/grpc/pull/15802 (where c++ installation instructions were moved so src/cpp, beside other changes)
=> Get rid of references to INSTALL.md

_sass/base/_common.scss, blog/index.html
This PR contains some small HTML/CSS changes for the gRPC blog related to the list of posts on the right side.
Before:
After:
=> Blog CSS adjustment

docs/quickstart/csharp.md
I've removed the referenced example because it doesn't exist in the examples directory. This probably needs to be adjusted.
=> Update C# doc

docs/tutorials/basic/csharp.md
As mentioned in https://github.com/grpc/grpc/issues/16397.
I grepped through the repository and didn't find any other occurrences.
=> Dont hardcode the tag version in C# docs

docs/quickstart/csharp.md, docs/tutorials/basic/csharp.md
Fixes https://github.com/grpc/grpc/issues/16397
We should hold merging until v1.15.0 is released (~about two weeks from now), because the changes to C# examples from https://github.com/grpc/grpc/pull/16144  won't be propagated to the release branch until then.
=> Update C# quickstart and tutorial

docs/talks/index.html
Link to "Building Microservices with gRPC and Kubernetes, 2016" is a 404 to Ustream.tv
=> Remove dead link

docs/reference/go/generated-code.md
In this page
https://grpc.io/docs/reference/go/generated-code
If you click on `Service Definitions ` you'll get **404**.
=> Fixing 404 for service definitions link

_includes/doc-call.html, _includes/doc-side-quickstart-nav.html, _includes/doc-side-tutorial-nav.html, docs/index.html, docs/quickstart/web.md, docs/tutorials/basic/web.md
Add Quickstart and Tutorial for gRPC-Web to main grpc.io website
cc: @wenbozhu
=> Add Quickstart and Tutorial for gRPC-Web

docs/guides/auth.md
As documented on https://grpc.io/grpc/python/grpc.html#grpc.ssl_channel_credentials
=> pass channel credentials as byte string

docs/quickstart/dart.md
We no longer support Dart 1.x.
=> dart-grpc: Raise Dart SDK requirement

docs/quickstart/csharp.md
removed extra packages folder from path
updated command to reflect full path for "grpc_csharp_plugin"..
protoc-gen-grpc plugin requires fullpath of "grpc_csharp_plugin" executable instead of short form with "~". Make sure to change <HOME_FOLDER phrase in below command according to your local machine.
=> csharp.md: changes to mac os build instructions.

docs/guides/concepts.md
Documented well in the bi-di case, but not explicitly spelled out in the other streaming cases.
=> gRPC guarantees the order of streaming messages

faq/index.html
Added link to gRPC release schedule and swapped the order of "When do gRPC releases happen?" and "How long are gRPC releases supported for?"
=> Add link to release schedule

docs/quickstart/csharp.md
Hey,
I belive there is a mistake in the path to Grpc.Tools in the example command for Linux in the documentation. When I tried running the example command displayed on the page (look below) I got an error saying that the path does not exist. It worked when I replaced the dot after *tools* in the current path (`~.nuget/packages/grpc.tools.1.16.0/`)  with a slash, which resulted in a valid path: `~/.nuget/packages/grpc.tools/1.16.0/`
=> The path to Grpc.Tools in the example command for Linux(or macOS) does not exist

docs/quickstart/python.md, docs/tutorials/basic/python.md
This reverts commit d9c953d22bb59f07d01e90053fee1673252e582c.
cc @hsaliak I'm not sure why this PR was merged. Unless I'm missing something, the reported error was because the *user's* protobuf file (not grpcio-tools itself) had a dependency on googleapis-common-protos. They should add this to their project's dependencies, it's not something required to use grpcio-tools or our quickstart or tutorial code.
=> Revert "Update to account for import error in generated python code"

docs/samples/index.md
https://github.com/kelseyhightower/helloworld is just a basic http server, having it linked here just confuses people.
=> Remove linked helloworld - it's not "Go Secure"

docs/quickstart/android.md
The project gradle wrapper is about to be removed https://github.com/grpc/grpc-java/pull/5141
=> Run the gradle wrapper in examples root directory

about/index.html, docs/quickstart/dart.md, docs/tutorials/basic/dart.md
We published a 1.0 version of the Dart gRPC package: https://pub.dartlang.org/packages/grpc#-analysis-tab-
This updated the documentation to remove statements that Dart is still in beta.
=> Take Dart gRPC to 1.0 stable

_posts/2018-12-18-grpc-dotnet-build.md
Fix both, to be on the safe side.
=> Rename invalid date 18-18 to 12-18; use &#58;` for  the `:`

docs/tutorials/basic/c.md, docs/tutorials/basic/csharp.md, docs/tutorials/basic/dart.md, docs/tutorials/basic/go.md, docs/tutorials/basic/java.md, docs/tutorials/basic/node.md, docs/tutorials/basic/objective-c.md, docs/tutorials/basic/python.md, docs/tutorials/basic/ruby.md
Proto3 haven't been in beta for a while, also removing the link to protobuf release notes which doesn't seem useful anymore for that reason.
=> Fixes in route guide protobuf intro

_posts/2019-01-08-state-of-grpc-web.md
Improbable has decided to disambiguate its client from the official one by using the organisation name, see https://github.com/improbable-eng/grpc-web/issues/289.
=> Update NPM link to Improbable client

docs/tutorials/basic/node.md
The stub is actually held in a var called "routeguide" and not "example". This change makes it consistent as per the rest of this documentation and the full sample code.
=> Fixing documentation typo

docs/guides/benchmarking.md
The old link leads to a personal dashboard of a team member (and there's no data).
=> Fix link to detailed C++ performance dashboard.

docs/tutorials/basic/go.md
When the server returns an error during a client-streaming RPC the error on the client side will be `io.EOF` in order to get the real message back from the server you need to call stream.CloseAndRecv() and then log that.
=> Update go client streaming example

_layouts/post.html
Completes #858 (I missed blog entries in the previous round because the `post` layout isn't based on the `default` layout).
=> Blog posts: add obsolete-page warning

release
Contributes to https://github.com/grpc/grpc.io/pull/542 cleanup. This site is obsolete, so /release shouldn't be used.
=> Drop /release
